@baseUrl = http://localhost:3333

# @name register_subscription
POST {{baseUrl}}/subscription
Content-Type: application/json

{
  "name": "Travis SCott",
  "email": "travis.scott@x.com",
  "event_id": "evt_01j8fqpxbpftqbf357xpejmg98"
}

###

# @name generate_referral_link
POST {{baseUrl}}/generate-referral-link
Content-Type: application/json

{
  "email": "travis.scott@x.com",
  "event_id": "evt_01j8fqpxbpftqbf357xpejmg98"
}

### 

# @name handle_referral_link
GET {{baseUrl}}/referral?token=66f9fc5d10d1ce1ae7c56cf46cfec11d&event_id=evt_01j8fqpxbpftqbf357xpejmg98

### 

# @name register_subscription_by_referral_link
POST {{baseUrl}}/subscription
Content-Type: application/json

{
  "name": "Garbini",
  "email": "travis-scotttt@email.com",
  "event_id": "evt_01j8fqpxbpftqbf357xpejmg98",
  "referral_link_token": "66f9fc5d10d1ce1ae7c56cf46cfec11d"
}