@baseUrl = http://localhost:3333

# @name register_subscription
POST {{baseUrl}}/subscription
Content-Type: application/json

{
  "name": "Abraham Lincoln",
  "email": "abraham.Lincoln5@email.com",
  "event_id": "evt_01j8694zh3e8s89a82g3jttyey"
}