name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:13.16.0
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: event-booster-test
        ports:
          - 5433:5432
      redis:
        image: bitnami/redis:latest
        env:
          REDIS_PASSWORD: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # ou qualquer versão que você deseja testar
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npm run db:migrate:test

      - name: Execute tests
        run: npm run test

      - name: Execute test coverage
        run: npm run test:coverage
